version: "1.0"
provider: "anthropic"
model: "claude-sonnet-4-0"
api_key: "${ANTHROPIC_API_KEY}"

rules:
  - name: api-compliance
    files:
      include: ["src/**/*.go"]
      exclude: ["*_test.go"]
    specs:
      - path: "docs/api-spec.md"
