version: "1.0"
provider: "anthropic"
model: "claude-sonnet-4-0"
api_key: "${ANTHROPIC_API_KEY}"
temperature: 0.0
timeout: 60
fail_on_issues: false

rules:
  - name: "case1"
    description: "Correct!"
    enabled: true
    files:
      include:
        - "./evals/cases/case1/impl.go"
    specs:
      - path: "./evals/cases/case1/spec.md"
    fail_on: "error"

  - name: "case2"
    description: |
      Subtract function is not implemented
    enabled: true
    files:
      include:
        - "./evals/cases/case2/impl.go"
    specs:
      - path: "./evals/cases/case2/spec.md"
    fail_on: "error"

  - name: "case3"
    description: |
      ProcessString has wrong signature - should return (string, error) but returns only string
      FormatMessage has wrong parameter types - should accept ...interface{} but accepts only one string
    enabled: true
    files:
      include:
        - "./evals/cases/case3/impl.go"
    specs:
      - path: "./evals/cases/case3/spec.md"
    fail_on: "error"

  - name: "case4"
    description: |
      IsValidEmail has incorrect logic - only checks for @ but not domain
      IsPositive has incorrect logic - returns true for 0 but should only return true for > 0
    enabled: true
    files:
      include:
        - "./evals/cases/case4/impl.go"
    specs:
      - path: "./evals/cases/case4/spec.md"
    fail_on: "error"

  - name: "case5"
    description: |
      Default value not implemented for function argument
    enabled: true
    files:
      include:
        - "./evals/cases/case5/impl.go"
    specs:
      - path: "./evals/cases/case5/spec.md"
    fail_on: "error"

  - name: "case6"
    description: |
      Complex file processing API implementation with multiple severity-level issues:

      ERROR level issues (3):
      - ProcessFile missing required 'options ProcessOptions' parameter per specification
      - Missing path traversal security validation (spec: "MUST validate file path to prevent directory traversal attacks")
      - ProcessBatch returns []*ProcessResult instead of []ProcessResult as specified

      WARNING level issues (5):
      - Missing corruption detection (spec: "MUST detect and reject corrupted files")
      - Missing recommended audit logging for ValidateFileSize
      - Inefficient O(n²) algorithm in ProcessBatch (nested loops)
      - Non-standard error message format (spec requires: "failed to process file [filename]: [reason]")
      - Missing optional caching implementation

      INFO level issues (4):
      - Undocumented default timeout value (30 seconds)
      - Undocumented MaxRetries default value
      - Additional utility functions not required by spec
      - Incomplete integrity validation (only checks file extension)
    enabled: true
    files:
      include:
        - "./evals/cases/case6/impl.go"
    specs:
      - path: "./evals/cases/case6/spec.md"
    fail_on: "error"
